### ISSUE TITLE
Dark theme is not applied

### ISSUE THREAD

**Issue by bartvdbraak** [rajnandan1/kener#123]
**Describe the bug**
When setting `theme: dark`, it still shows light theme.

**To Reproduce**
1. Have `theme: dark` in `/app/config/site.yaml`
2. Visit page
4. Notice light theme regardless of local browser cache / cookies

**Expected behavior**
To show a dark theme

**Desktop (please complete the following information):**
 - OS: Linux (Gentoo)
 - Browser: Firefox 128.0b6, Google Chrome 131.0.6778.69

**Comment by rajnandan1** [comment]
Thanks for reporting this ❤️ 

I have fixed it
