### ISSUE TITLE
Slow to render main page

### ISSUE THREAD

**Issue by rayjanoka** [rajnandan1/kener#40]
**Describe the bug**

Hi, love the site, we are using it in production now!

But it is taking over 2 seconds to render the main page with 5 monitors. 

Is there anything we can do to speed it up? Maybe send the headers to allow caching for a minute or two?

Lighthouse Report
![image](https://github.com/rajnandan1/kener/assets/18078751/cddfe2a7-f3d5-4a11-a073-1569a73ca823)

**Comment by rajnandan1** [comment]
Is there a public link? Would like to do a deeper analysis

**Comment by rayjanoka** [comment]
> Is there a public link? Would like to do a deeper analysis

yes! https://status.minehut.com

**Comment by rajnandan1** [comment]
I can see there is no reverse proxy. one thing you can do for now is add gzip compression 
You can modify the prod.js file
https://expressjs.com/en/advanced/best-practice-performance.html#use-gzip-compression

I will add these functionalities as configuration

**Comment by rayjanoka** [comment]
Ok, gzip compression is something. 

Actually I am running traefik as my proxy, is there something we could do there? thanks!

**Comment by rajnandan1** [comment]
I  see the scores have improved a lot. Did you do something?

<img width="1167" alt="Screenshot 2024-01-25 at 11 07 00 PM" src="https://github.com/rajnandan1/kener/assets/16224367/d3a4ba19-8a33-4642-80c3-cf2e1123c2f0">

**Comment by rayjanoka** [comment]
no, the score was always high, it doesn't reflect the delay. if you look down further you will see it in the details.

The issue appears to be a mixture of reading the json and talking to github.

On my local system with a small json and no github configured I get 200ms, with a larger json (8 days worth) it goes up quite a bit to 1.2 seconds, then when I connect it to github it goes up to 3.5 seconds.

![image](https://github.com/rajnandan1/kener/assets/18078751/eb19e68b-63b3-4ae7-9ff7-06853dfe113b)

**Comment by rajnandan1** [comment]
I have done some optimization, do test. Closing this ticket. 
Instead of making multiple API calls, calling Github just once on initial load.
Please free to reopen

**Comment by rayjanoka** [comment]
appreciate it @rajnandan1. I will give it a go!
