### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by jdmedlock** [rajnandan1/kener#49]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem. It's purely a new feature request.

**Describe the solution you'd like**
When a monitored service doesn't respond to Kerner's health check there should be an option for it to email an interested party. For example, the admin for that service. Other notification types would be nice, like SMS or DMing a person on a site like Discord or Slack, but not required for the initial implementation of this feature.

**Describe alternatives you've considered**

**Additional context**
The email notification interval should be separate from the polling interval for the health check to prevent flooding the interested parties inbox. It may also be useful to implement this as two separate intervals - one interval for the initial detection of the outage and a second interval used to send reminders. For example, 1 minute for the first and increments of 15 minutes for the second.

**Comment by jdmedlock** [comment]
I know this is in your roadmap for upcoming features. But, I hope this is useful none-the-less.

**Comment by rajnandan1** [comment]
This has been updated now
