### ISSUE TITLE
reading the per minute json data is too slow

### ISSUE THREAD

**Issue by rayjanoka** [rajnandan1/kener#50]
**Describe the bug**
hey, love the site! But my site is taking 8+ seconds to respond now that we have 20+ days across 5 monitors.

**Expected behavior**
reasonable response time for webpage is <1 second

**Additional context**
Could we summarize the json files into something that is faster to read on page load? Perhaps a separate json file that has pre-computed the per day counts for UP/DOWN/DEGRADED so it doesn't need to count every minute on every page load? That should be a lot faster. Once we hit 90 days that'll be `60 * 24 * 90 = 130k` data points per monitor, and `130k * 5 monitors = 650k` datapoints to process on every page load.

thanks!

**Comment by rajnandan1** [comment]
Hey @rayjanoka was AFK for a week, 
That is a good suggestion, let me try it

**Comment by rajnandan1** [comment]
Having said that
If you look at this site
https://statuspage.cashfree.com/category-Payment%20Gateway%20APIs
it has lot of monitors but loads under 1 sec

Do you have the latest pull?

**Comment by rajnandan1** [comment]
It is done in the last code push

**Comment by rayjanoka** [comment]
I do have some questionable hacks, hehe. but this is much better!!!

![image](https://github.com/rajnandan1/kener/assets/18078751/4370bd7c-58b8-4258-bf0a-6870d4e6b1ba)

I'm going to create 2 or 3 more tickets so you can see if you are interested implement them properly. thank you!! 🚀
