### ISSUE TITLE
Show daily status bar as Red only if it passes a threshold

### ISSUE THREAD

**Issue by rayjanoka** [rajnandan1/kener#54]
**Is your feature request related to a problem? Please describe.**

Some of the services that I am monitoring are not the most reliable so sometimes I get 1 or 2 random missed pings per day and then I get a red bar for that whole day and it looks bad. I would like to set a threshold of down minutes per day before I get a red bar.

**Describe the solution you'd like**

I would like a threshold setting where I can set it to only show the day as `DOWN` (red) if it was down for more than N minutes. Most likely having this setting per monitor would be best, although I'm fine using it globally across all monitors.

**Describe alternatives you've considered**

None

**Additional context**

I did something like this in `ninety.js` and it seems to work.

from
```javascript
    if (dayData.DOWN > 0) {
        cssClass = StatusObj.DOWN;
        message = getDayMessage("Down", dayData.DOWN);
    }
```

to
```javascript
    if (dayData.DOWN > 3) { // modification to suppress a few misses
        cssClass = StatusObj.DOWN;
        message = getDayMessage("Down", dayData.DOWN);
    }
```

The simple way I implement it here may be problematic as a real outage will have to pass this threshold before it will be displayed on the page, not sure if there is a way around that at least for an outage declared through a GitHub issue (I have not tested this).

**Comment by rajnandan1** [comment]
<img width="1035" alt="Screenshot 2024-04-30 at 11 17 17 AM" src="https://github.com/rajnandan1/kener/assets/16224367/6ed02a62-024b-44f0-a01a-2885463f9f4b">
