### ISSUE TITLE
docker image seems cannnot work

### ISSUE THREAD

**Issue by liam-pat** [rajnandan1/kener#56]
**Describe the bug**
docker cannot  run. need commit a new tag to docker hub.

<<<<
kener  | Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/app/src/lib/helpers.js' imported from /app/scripts/ninety.js
kener  |     at new NodeError (node:internal/errors:405:5)
kener  |     at finalizeResolution (node:internal/modules/esm/resolve:327:11)
kener  |     at moduleResolve (node:internal/modules/esm/resolve:980:10)
kener  |     at defaultResolve (node:internal/modules/esm/resolve:1193:11)
kener  |     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:403:12)
kener  |     at ModuleLoader.resolve (node:internal/modules/esm/loader:372:25)
kener  |     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:249:38)
kener  |     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
kener  |     at link (node:internal/modules/esm/module_job:75:36) {
kener  |   url: 'file:///app/src/lib/helpers.js',
kener  |   code: 'ERR_MODULE_NOT_FOUND'
kener  | }

**Comment by rajnandan1** [comment]
Fixed

**Comment by marvel00000** [comment]
docker image rajnandan1/kener:0.0.8 do not work too, logs :

kener  | Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/app/src/lib/helpers.js' imported from /app/scripts/ninety.js
kener  |     at new NodeError (node:internal/errors:405:5)
kener  |     at finalizeResolution (node:internal/modules/esm/resolve:327:11)
kener  |     at moduleResolve (node:internal/modules/esm/resolve:980:10)
kener  |     at defaultResolve (node:internal/modules/esm/resolve:1193:11)
kener  |     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:403:12)
kener  |     at ModuleLoader.resolve (node:internal/modules/esm/loader:372:25)
kener  |     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:249:38)
kener  |     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
kener  |     at link (node:internal/modules/esm/module_job:75:36) {
kener  |   url: 'file:///app/src/lib/helpers.js',
kener  |   code: 'ERR_MODULE_NOT_FOUND'
kener  | }
kener  |
kener  | Node.js v18.19.1
