### ISSUE TITLE
Document 'timeout'

### ISSUE THREAD

**Issue by ohhdemgirls** [rajnandan1/kener#57]
> https://kener.ing/docs#h2understanding-monitors

`timeout: 4000` is in the sample config for api/post request....

1. Can `timeout` be used with api **get** requests?
2. What is the timescale used? 4000 is equal to?

**Comment by rajnandan1** [comment]
1. timeout can be used in get. Default is 10 secs
2. Unit is in milliseconds

Updated the docs
