### ISSUE TITLE
Widget error

### ISSUE THREAD

**Issue by viriatusX** [rajnandan1/kener#59]
Hi
it's not possible add widget / script to any site.
It's show" Refused to display 'https://xxxxxxxxx' in a frame because it set 'X-Frame-Options' to 'sameorigin'."

**Comment by rajnandan1** [comment]
This is fixed

**Comment by yuzh2001** [comment]
```
Invalid 'X-Frame-Options' header encountered when loading 'https://……/': 'None' is not a recognized directive. The header will be ignored.
```

Hi, this problem remains.
