### ISSUE TITLE
Assets from static folder are not copied to the app

### ISSUE THREAD

**Issue by xHyroM** [rajnandan1/kener#61]
https://github.com/rajnandan1/kener/blob/f921df0e97efb530e63a910dd8fce048872617e1/Dockerfile#L59

I'm not sure if this works, as i tried to setup kener and my files from static/ folder doesn't work on deployed website. I'm using docker compose & portainer.

![image](https://github.com/rajnandan1/kener/assets/56601352/8167e610-a09c-4103-b41d-bc2750ccbbd3)

**Comment by adhadse** [comment]
Facing same issue, running on podman rootless containers, can't get the logo to show up.

**Comment by rajnandan1** [comment]
This fixed in the latest release
Have update the docs here 
<img width="1055" alt="Screenshot 2024-04-22 at 10 08 17 PM" src="https://github.com/rajnandan1/kener/assets/16224367/14d49dd7-b22e-4e3c-a689-f98a0ee15f1a">
