### ISSUE TITLE
deploy kener under a subpath on kubernetes ingress

### ISSUE THREAD

**Issue by bisegni** [rajnandan1/kener#68]
**Is your feature request related to a problem? Please describe.**
i cannot use the UI if the ingress uses the subpath ex: https://hostname/status

**Describe the solution you'd like**
update UI code

**Describe alternatives you've considered**

**Additional context**

**Comment by rajnandan1** [comment]
Please find the docs
https://kener.ing/docs#h2base-path

**Comment by bisegni** [comment]
hi thank you @rajnandan1, is the path been merged into main?

**Comment by rajnandan1** [comment]
@bisegni yes
