### ISSUE TITLE
Origin wildcard for ips

### ISSUE THREAD

**Issue by c4g7-dev** [rajnandan1/kener#80]
**Is your feature request related to a problem? Please describe.**
i cannot make a GET request from my proxied domain due to "invalid IP"

**Describe the solution you'd like**
I would like to have the option to define allowed origins or domains(wildcards).

**Comment by rajnandan1** [comment]
I did not understand the requirement. 
Are you trying to make an API call and you have set [API_IP](https://kener.ing/kener-docs/docs/environment-vars#api_ip) and it is giving invalid IP error?

**Comment by KenleyundLeon** [comment]
well me and him are trying to call the API via reqbin.com and it does give an invalid IP error but if we try it on our own PC's/machines everything works fine we are thinking it could be the Origin setting.

**Comment by KenleyundLeon** [comment]
because it would be really sad if we code smth with the API and it throws an 401 invalid IP error when we host it yk?

**Comment by rajnandan1** [comment]
Updated here
https://kener.ing/kener-docs/docs/environment-vars#api_ip

**Comment by c4g7-dev** [comment]
How can is sent a Webhook to discord when a Monitor goes down?
