### ISSUE TITLE
Request HTTPS

### ISSUE THREAD

**Issue by rafaelferreiras** [rajnandan1/kener#81]
**Describe the bug**
Hello, first I would like to thank you for the excellent work. This application is wonderful.

We are experiencing the error: "self-signed certificate in certificate chain". Can you give us a tip on how to fix it? We want to apply the configuration:

rejectUnauthorized: false

**Comment by rajnandan1** [comment]
So you can add your self signed ca 
You can try this, not sure if it will work

https://github.com/rajnandan1/kener/blob/main/scripts/cron-minute.js#L167
```
const agent = new https.Agent({
  ca: fs.readFileSync('path/to/self-signed-certificate.pem')
});
	const options = {
		method: method,
		headers: headers,
		timeout: timeout,
		transformResponse: (r) => r
	};
```

**Comment by rajnandan1** [comment]
Closing the issue as there has been not update from OP
