### ISSUE TITLE
problem with .env file

### ISSUE THREAD

**Issue by ArtyomCZ** [rajnandan1/kener#92]
**Describe the bug**
I created an .env file and defined PUBLIC_KENER_FOLDER and GH_TOKEN. But it seems it is not read when `npm run build` so I can't run Kener in production mode. Dev mode works fine but without environment variables.

**To Reproduce**
1. Create fork of Kener repository
2. Create .env file with variables
3. npm i
4. mv config/site.example.yaml config/site.yaml
5. mv config/monitors.example.yaml config/monitors.yaml
6. npm run build

**Expected behavior**
I don't know if I'm missing something, but I assume this should work.

**Screenshots**
![image](https://github.com/rajnandan1/kener/assets/16862369/33183b11-c97b-4e45-aec3-0cf376be2724)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - IDE: Jetbrains Webstorm

**Comment by rajnandan1** [comment]
I have added support of .env file in the latest build
